Model
Rseiji/TCC-2020 pull request #7
Opened 2020-10-15 02:43 UTC by Rseiji

1. Tokenizer code importable from `.py` script
2. Model code importable from `.py` script
3. Analysis code MVP implemented. The idea is to help processes by automating generation of analysis metrics.
4. Google colab's used notebook commited here as a temporary version of model execution code.

Local GPU adaption isn't resolved yet. Demands additional local configurations setup.

2020-10-15 17:52 UTC, douglasramos commented on chess_commentary_model/bert_tokenizer.py
> +        input_ids = tokenizer.encode(sent, add_special_tokens=True)
🚲  tokenizer e input_ids não são necessário nesse método

2020-10-15 18:15 UTC, douglasramos requested changes

2020-10-15 18:15 UTC, douglasramos commented on chess_commentary_model/bert_tokenizer.py
> +def make_dataset(sentences, labels, max_phrase_len=None):
talvez um nome melhor aqui fosse tokenize_dataset

2020-10-15 18:15 UTC, douglasramos commented on chess_commentary_model/bert_tokenizer.py
> +    labels = torch.tensor(labels)
sei que talvez no python isso seja aceitável, mas acho melhor setar em outra variável. 
Ficaria algo como:
`labels_tensor_obj = torch.tensor(labels)`

2020-10-15 18:15 UTC, douglasramos commented on chess_commentary_model/classification_analysis.py
> +def save_analysis(results, conf_mat, file_name_analysis, file_name_conf_mat, path=''):
🌟

2020-10-15 18:15 UTC, douglasramos commented on chess_commentary_model/classification_analysis.py
> +    result_concatenation = pd.DataFrame({'pred': flat_predictions, 'labels_tmp': flat_true_labels})
por que chamamos de 'labels_tmp'?

2020-10-15 18:15 UTC, douglasramos commented on chess_commentary_model/classification_analysis.py
> +def compile_results(flat_predictions, flat_true_labels, test_set):
Ficou um pouco confuso o que esse método está fazendo exatamente. Talvez vale um comentário explicando o que ele faz e/ou melhorar um pouco os nomes das variáveis pra dar mais semântica

2020-10-15 18:15 UTC, douglasramos commented on chess_commentary_model/classification_analysis.py
> +    labels_0 = df[df['label'] == 0]['label']
conseguimos ser mais específicos do que usar o sufixo 0 ou 1?

2020-10-15 18:15 UTC, douglasramos commented on chess_commentary_model/transformers_model.py
> +def format_time(elapsed):
Esse método não parece ter muito a ver com esse arquivo. Talvez ele possa estar em um arquivo chamado time_utils.py

2020-10-15 18:15 UTC, douglasramos commented on chess_commentary_model/transformers_model.py
> +##############################
input_ids está em todo arquivo e eu ainda não sei o que é essa variável kkkk

2020-10-18 13:51 UTC, Rseiji commented on chess_commentary_model/classification_analysis.py
> +    result_concatenation = pd.DataFrame({'pred': flat_predictions, 'labels_tmp': flat_true_labels})
Foi só um check extra para garantir que o ordenamento das labels nos tensores não se alterou em relação ao dataset. É portanto redundante em comparação com a coluna 'label'

2020-10-18 13:51 UTC, Rseiji commented on chess_commentary_model/classification_analysis.py
> +    labels_0 = df[df['label'] == 0]['label']
Acho que tá bom assim. É um problema de classificação, tá explicito o que quer dizer

2020-10-18 13:56 UTC, Rseiji commented on chess_commentary_model/transformers_model.py
> +def format_time(elapsed):
Isso aqui era pq antes o modelo cronometrava o tempo de execução. Tava dando pau e aí tirei essa funcionalidade. Futuramente, talvez seja bom implementar dnv isso (ok, em um `utils`), mas por hora vou só deletar esse método, que não está sendo usado.

2020-10-18 14:01 UTC, Rseiji commented on chess_commentary_model/transformers_model.py
> +##############################
troquei por tokenized_sentences. Aparentemente se trata de um argumento do objeto que faz a tokenização, do qual extraímos as sentenças tokenizadas pelo bert.

2020-10-18 14:02 UTC, Rseiji commented on chess_commentary_model/bert_tokenizer.py
> +    input_ids = []
ver resposta ao ultimo comentario desse code review

2020-10-18 16:47 UTC, douglasramos commented on chess_commentary_model/transformers_model.py
> +##############################
boa!

2020-10-18 16:48 UTC, douglasramos commented on chess_commentary_model/transformers_model.py
> +def format_time(elapsed):
beleza!

2020-10-18 16:48 UTC, douglasramos commented on chess_commentary_model/classification_analysis.py
> +    labels_0 = df[df['label'] == 0]['label']
boa, verdade, não tinha avaliado isso

2020-10-18 16:49 UTC, douglasramos commented on chess_commentary_model/classification_analysis.py
> +    result_concatenation = pd.DataFrame({'pred': flat_predictions, 'labels_tmp': flat_true_labels})
beleza

2020-10-18 16:51 UTC, douglasramos approved these changes
LGTM!!

2020-10-23 19:03 UTC, merged